/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding.verify'
import { Route as OnboardingValuesRouteImport } from './routes/onboarding.values'
import { Route as OnboardingPromptsRouteImport } from './routes/onboarding.prompts'
import { Route as OnboardingPhotosRouteImport } from './routes/onboarding.photos'
import { Route as OnboardingPhotoReviewRouteImport } from './routes/onboarding.photo-review'
import { Route as OnboardingPaceRouteImport } from './routes/onboarding.pace'
import { Route as OnboardingIntentRouteImport } from './routes/onboarding.intent'
import { Route as OnboardingErrorRouteImport } from './routes/onboarding.error'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as OnboardingCapacityRouteImport } from './routes/onboarding.capacity'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as MainProfileRouteImport } from './routes/_main.profile'
import { Route as MainHomeRouteImport } from './routes/_main.home'
import { Route as MainGrowthRouteImport } from './routes/_main.growth'
import { Route as MainDiscoverRouteImport } from './routes/_main.discover'
import { Route as MainConnectionsRouteImport } from './routes/_main.connections'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as MainDiscoverIndexRouteImport } from './routes/_main.discover.index'
import { Route as MainHomeReflectionRouteImport } from './routes/_main.home.reflection'
import { Route as MainHomeCoachRouteImport } from './routes/_main.home.coach'
import { Route as MainHomeCheckInRouteImport } from './routes/_main.home.check-in'
import { Route as MainDiscoverQuietDayRouteImport } from './routes/_main.discover.quiet-day'
import { Route as MainDiscoverIdRouteImport } from './routes/_main.discover.$id'
import { Route as MainConnectionsIdRouteImport } from './routes/_main.connections.$id'
import { Route as MainDiscoverIdAttunedRouteImport } from './routes/_main.discover.$id_.attuned'
import { Route as MainDiscoverIdInsightsConnectionLanguagesRouteImport } from './routes/_main.discover.$id_.insights.connection-languages'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingValuesRoute = OnboardingValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPromptsRoute = OnboardingPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPhotosRoute = OnboardingPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPhotoReviewRoute = OnboardingPhotoReviewRouteImport.update({
  id: '/photo-review',
  path: '/photo-review',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPaceRoute = OnboardingPaceRouteImport.update({
  id: '/pace',
  path: '/pace',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingIntentRoute = OnboardingIntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingErrorRoute = OnboardingErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCapacityRoute = OnboardingCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainGrowthRoute = MainGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => MainRoute,
} as any)
const MainDiscoverRoute = MainDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => MainRoute,
} as any)
const MainConnectionsRoute = MainConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => MainRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const MainDiscoverIndexRoute = MainDiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainDiscoverRoute,
} as any)
const MainHomeReflectionRoute = MainHomeReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => MainHomeRoute,
} as any)
const MainHomeCoachRoute = MainHomeCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => MainHomeRoute,
} as any)
const MainHomeCheckInRoute = MainHomeCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => MainHomeRoute,
} as any)
const MainDiscoverQuietDayRoute = MainDiscoverQuietDayRouteImport.update({
  id: '/quiet-day',
  path: '/quiet-day',
  getParentRoute: () => MainDiscoverRoute,
} as any)
const MainDiscoverIdRoute = MainDiscoverIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainDiscoverRoute,
} as any)
const MainConnectionsIdRoute = MainConnectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainConnectionsRoute,
} as any)
const MainDiscoverIdAttunedRoute = MainDiscoverIdAttunedRouteImport.update({
  id: '/$id_/attuned',
  path: '/$id/attuned',
  getParentRoute: () => MainDiscoverRoute,
} as any)
const MainDiscoverIdInsightsConnectionLanguagesRoute =
  MainDiscoverIdInsightsConnectionLanguagesRouteImport.update({
    id: '/$id_/insights/connection-languages',
    path: '/$id/insights/connection-languages',
    getParentRoute: () => MainDiscoverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/connections': typeof MainConnectionsRouteWithChildren
  '/discover': typeof MainDiscoverRouteWithChildren
  '/growth': typeof MainGrowthRoute
  '/home': typeof MainHomeRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/capacity': typeof OnboardingCapacityRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/error': typeof OnboardingErrorRoute
  '/onboarding/intent': typeof OnboardingIntentRoute
  '/onboarding/pace': typeof OnboardingPaceRoute
  '/onboarding/photo-review': typeof OnboardingPhotoReviewRoute
  '/onboarding/photos': typeof OnboardingPhotosRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/values': typeof OnboardingValuesRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/connections/$id': typeof MainConnectionsIdRoute
  '/discover/$id': typeof MainDiscoverIdRoute
  '/discover/quiet-day': typeof MainDiscoverQuietDayRoute
  '/home/check-in': typeof MainHomeCheckInRoute
  '/home/coach': typeof MainHomeCoachRoute
  '/home/reflection': typeof MainHomeReflectionRoute
  '/discover/': typeof MainDiscoverIndexRoute
  '/discover/$id/attuned': typeof MainDiscoverIdAttunedRoute
  '/discover/$id/insights/connection-languages': typeof MainDiscoverIdInsightsConnectionLanguagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof AuthSigninRoute
  '/connections': typeof MainConnectionsRouteWithChildren
  '/growth': typeof MainGrowthRoute
  '/home': typeof MainHomeRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/capacity': typeof OnboardingCapacityRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/error': typeof OnboardingErrorRoute
  '/onboarding/intent': typeof OnboardingIntentRoute
  '/onboarding/pace': typeof OnboardingPaceRoute
  '/onboarding/photo-review': typeof OnboardingPhotoReviewRoute
  '/onboarding/photos': typeof OnboardingPhotosRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/values': typeof OnboardingValuesRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/connections/$id': typeof MainConnectionsIdRoute
  '/discover/$id': typeof MainDiscoverIdRoute
  '/discover/quiet-day': typeof MainDiscoverQuietDayRoute
  '/home/check-in': typeof MainHomeCheckInRoute
  '/home/coach': typeof MainHomeCoachRoute
  '/home/reflection': typeof MainHomeReflectionRoute
  '/discover': typeof MainDiscoverIndexRoute
  '/discover/$id/attuned': typeof MainDiscoverIdAttunedRoute
  '/discover/$id/insights/connection-languages': typeof MainDiscoverIdInsightsConnectionLanguagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_main/connections': typeof MainConnectionsRouteWithChildren
  '/_main/discover': typeof MainDiscoverRouteWithChildren
  '/_main/growth': typeof MainGrowthRoute
  '/_main/home': typeof MainHomeRouteWithChildren
  '/_main/profile': typeof MainProfileRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/capacity': typeof OnboardingCapacityRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/error': typeof OnboardingErrorRoute
  '/onboarding/intent': typeof OnboardingIntentRoute
  '/onboarding/pace': typeof OnboardingPaceRoute
  '/onboarding/photo-review': typeof OnboardingPhotoReviewRoute
  '/onboarding/photos': typeof OnboardingPhotosRoute
  '/onboarding/prompts': typeof OnboardingPromptsRoute
  '/onboarding/values': typeof OnboardingValuesRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_main/connections/$id': typeof MainConnectionsIdRoute
  '/_main/discover/$id': typeof MainDiscoverIdRoute
  '/_main/discover/quiet-day': typeof MainDiscoverQuietDayRoute
  '/_main/home/check-in': typeof MainHomeCheckInRoute
  '/_main/home/coach': typeof MainHomeCoachRoute
  '/_main/home/reflection': typeof MainHomeReflectionRoute
  '/_main/discover/': typeof MainDiscoverIndexRoute
  '/_main/discover/$id_/attuned': typeof MainDiscoverIdAttunedRoute
  '/_main/discover/$id_/insights/connection-languages': typeof MainDiscoverIdInsightsConnectionLanguagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/connections'
    | '/discover'
    | '/growth'
    | '/home'
    | '/profile'
    | '/onboarding/$step'
    | '/onboarding/capacity'
    | '/onboarding/complete'
    | '/onboarding/error'
    | '/onboarding/intent'
    | '/onboarding/pace'
    | '/onboarding/photo-review'
    | '/onboarding/photos'
    | '/onboarding/prompts'
    | '/onboarding/values'
    | '/onboarding/verify'
    | '/onboarding/'
    | '/connections/$id'
    | '/discover/$id'
    | '/discover/quiet-day'
    | '/home/check-in'
    | '/home/coach'
    | '/home/reflection'
    | '/discover/'
    | '/discover/$id/attuned'
    | '/discover/$id/insights/connection-languages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/connections'
    | '/growth'
    | '/home'
    | '/profile'
    | '/onboarding/$step'
    | '/onboarding/capacity'
    | '/onboarding/complete'
    | '/onboarding/error'
    | '/onboarding/intent'
    | '/onboarding/pace'
    | '/onboarding/photo-review'
    | '/onboarding/photos'
    | '/onboarding/prompts'
    | '/onboarding/values'
    | '/onboarding/verify'
    | '/onboarding'
    | '/connections/$id'
    | '/discover/$id'
    | '/discover/quiet-day'
    | '/home/check-in'
    | '/home/coach'
    | '/home/reflection'
    | '/discover'
    | '/discover/$id/attuned'
    | '/discover/$id/insights/connection-languages'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/onboarding'
    | '/_auth/signin'
    | '/_main/connections'
    | '/_main/discover'
    | '/_main/growth'
    | '/_main/home'
    | '/_main/profile'
    | '/onboarding/$step'
    | '/onboarding/capacity'
    | '/onboarding/complete'
    | '/onboarding/error'
    | '/onboarding/intent'
    | '/onboarding/pace'
    | '/onboarding/photo-review'
    | '/onboarding/photos'
    | '/onboarding/prompts'
    | '/onboarding/values'
    | '/onboarding/verify'
    | '/onboarding/'
    | '/_main/connections/$id'
    | '/_main/discover/$id'
    | '/_main/discover/quiet-day'
    | '/_main/home/check-in'
    | '/_main/home/coach'
    | '/_main/home/reflection'
    | '/_main/discover/'
    | '/_main/discover/$id_/attuned'
    | '/_main/discover/$id_/insights/connection-languages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/values': {
      id: '/onboarding/values'
      path: '/values'
      fullPath: '/onboarding/values'
      preLoaderRoute: typeof OnboardingValuesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/prompts': {
      id: '/onboarding/prompts'
      path: '/prompts'
      fullPath: '/onboarding/prompts'
      preLoaderRoute: typeof OnboardingPromptsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/photos': {
      id: '/onboarding/photos'
      path: '/photos'
      fullPath: '/onboarding/photos'
      preLoaderRoute: typeof OnboardingPhotosRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/photo-review': {
      id: '/onboarding/photo-review'
      path: '/photo-review'
      fullPath: '/onboarding/photo-review'
      preLoaderRoute: typeof OnboardingPhotoReviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/pace': {
      id: '/onboarding/pace'
      path: '/pace'
      fullPath: '/onboarding/pace'
      preLoaderRoute: typeof OnboardingPaceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/intent': {
      id: '/onboarding/intent'
      path: '/intent'
      fullPath: '/onboarding/intent'
      preLoaderRoute: typeof OnboardingIntentRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/error': {
      id: '/onboarding/error'
      path: '/error'
      fullPath: '/onboarding/error'
      preLoaderRoute: typeof OnboardingErrorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/capacity': {
      id: '/onboarding/capacity'
      path: '/capacity'
      fullPath: '/onboarding/capacity'
      preLoaderRoute: typeof OnboardingCapacityRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/growth': {
      id: '/_main/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof MainGrowthRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/discover': {
      id: '/_main/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof MainDiscoverRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/connections': {
      id: '/_main/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof MainConnectionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/discover/': {
      id: '/_main/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof MainDiscoverIndexRouteImport
      parentRoute: typeof MainDiscoverRoute
    }
    '/_main/home/reflection': {
      id: '/_main/home/reflection'
      path: '/reflection'
      fullPath: '/home/reflection'
      preLoaderRoute: typeof MainHomeReflectionRouteImport
      parentRoute: typeof MainHomeRoute
    }
    '/_main/home/coach': {
      id: '/_main/home/coach'
      path: '/coach'
      fullPath: '/home/coach'
      preLoaderRoute: typeof MainHomeCoachRouteImport
      parentRoute: typeof MainHomeRoute
    }
    '/_main/home/check-in': {
      id: '/_main/home/check-in'
      path: '/check-in'
      fullPath: '/home/check-in'
      preLoaderRoute: typeof MainHomeCheckInRouteImport
      parentRoute: typeof MainHomeRoute
    }
    '/_main/discover/quiet-day': {
      id: '/_main/discover/quiet-day'
      path: '/quiet-day'
      fullPath: '/discover/quiet-day'
      preLoaderRoute: typeof MainDiscoverQuietDayRouteImport
      parentRoute: typeof MainDiscoverRoute
    }
    '/_main/discover/$id': {
      id: '/_main/discover/$id'
      path: '/$id'
      fullPath: '/discover/$id'
      preLoaderRoute: typeof MainDiscoverIdRouteImport
      parentRoute: typeof MainDiscoverRoute
    }
    '/_main/connections/$id': {
      id: '/_main/connections/$id'
      path: '/$id'
      fullPath: '/connections/$id'
      preLoaderRoute: typeof MainConnectionsIdRouteImport
      parentRoute: typeof MainConnectionsRoute
    }
    '/_main/discover/$id_/attuned': {
      id: '/_main/discover/$id_/attuned'
      path: '/$id/attuned'
      fullPath: '/discover/$id/attuned'
      preLoaderRoute: typeof MainDiscoverIdAttunedRouteImport
      parentRoute: typeof MainDiscoverRoute
    }
    '/_main/discover/$id_/insights/connection-languages': {
      id: '/_main/discover/$id_/insights/connection-languages'
      path: '/$id/insights/connection-languages'
      fullPath: '/discover/$id/insights/connection-languages'
      preLoaderRoute: typeof MainDiscoverIdInsightsConnectionLanguagesRouteImport
      parentRoute: typeof MainDiscoverRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainConnectionsRouteChildren {
  MainConnectionsIdRoute: typeof MainConnectionsIdRoute
}

const MainConnectionsRouteChildren: MainConnectionsRouteChildren = {
  MainConnectionsIdRoute: MainConnectionsIdRoute,
}

const MainConnectionsRouteWithChildren = MainConnectionsRoute._addFileChildren(
  MainConnectionsRouteChildren,
)

interface MainDiscoverRouteChildren {
  MainDiscoverIdRoute: typeof MainDiscoverIdRoute
  MainDiscoverQuietDayRoute: typeof MainDiscoverQuietDayRoute
  MainDiscoverIndexRoute: typeof MainDiscoverIndexRoute
  MainDiscoverIdAttunedRoute: typeof MainDiscoverIdAttunedRoute
  MainDiscoverIdInsightsConnectionLanguagesRoute: typeof MainDiscoverIdInsightsConnectionLanguagesRoute
}

const MainDiscoverRouteChildren: MainDiscoverRouteChildren = {
  MainDiscoverIdRoute: MainDiscoverIdRoute,
  MainDiscoverQuietDayRoute: MainDiscoverQuietDayRoute,
  MainDiscoverIndexRoute: MainDiscoverIndexRoute,
  MainDiscoverIdAttunedRoute: MainDiscoverIdAttunedRoute,
  MainDiscoverIdInsightsConnectionLanguagesRoute:
    MainDiscoverIdInsightsConnectionLanguagesRoute,
}

const MainDiscoverRouteWithChildren = MainDiscoverRoute._addFileChildren(
  MainDiscoverRouteChildren,
)

interface MainHomeRouteChildren {
  MainHomeCheckInRoute: typeof MainHomeCheckInRoute
  MainHomeCoachRoute: typeof MainHomeCoachRoute
  MainHomeReflectionRoute: typeof MainHomeReflectionRoute
}

const MainHomeRouteChildren: MainHomeRouteChildren = {
  MainHomeCheckInRoute: MainHomeCheckInRoute,
  MainHomeCoachRoute: MainHomeCoachRoute,
  MainHomeReflectionRoute: MainHomeReflectionRoute,
}

const MainHomeRouteWithChildren = MainHomeRoute._addFileChildren(
  MainHomeRouteChildren,
)

interface MainRouteChildren {
  MainConnectionsRoute: typeof MainConnectionsRouteWithChildren
  MainDiscoverRoute: typeof MainDiscoverRouteWithChildren
  MainGrowthRoute: typeof MainGrowthRoute
  MainHomeRoute: typeof MainHomeRouteWithChildren
  MainProfileRoute: typeof MainProfileRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainConnectionsRoute: MainConnectionsRouteWithChildren,
  MainDiscoverRoute: MainDiscoverRouteWithChildren,
  MainGrowthRoute: MainGrowthRoute,
  MainHomeRoute: MainHomeRouteWithChildren,
  MainProfileRoute: MainProfileRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
  OnboardingCapacityRoute: typeof OnboardingCapacityRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingErrorRoute: typeof OnboardingErrorRoute
  OnboardingIntentRoute: typeof OnboardingIntentRoute
  OnboardingPaceRoute: typeof OnboardingPaceRoute
  OnboardingPhotoReviewRoute: typeof OnboardingPhotoReviewRoute
  OnboardingPhotosRoute: typeof OnboardingPhotosRoute
  OnboardingPromptsRoute: typeof OnboardingPromptsRoute
  OnboardingValuesRoute: typeof OnboardingValuesRoute
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
  OnboardingCapacityRoute: OnboardingCapacityRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingErrorRoute: OnboardingErrorRoute,
  OnboardingIntentRoute: OnboardingIntentRoute,
  OnboardingPaceRoute: OnboardingPaceRoute,
  OnboardingPhotoReviewRoute: OnboardingPhotoReviewRoute,
  OnboardingPhotosRoute: OnboardingPhotosRoute,
  OnboardingPromptsRoute: OnboardingPromptsRoute,
  OnboardingValuesRoute: OnboardingValuesRoute,
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
